Minor Chem Fixes
GregTechCEu/gregicality-science pull request #69
Opened 2022-08-18 14:17 UTC by pablocnvs

Fixes #63 , #61 , #59  , #58, as well as inconsistencies with the handling of Ammonium Chloride

2022-08-18 15:24 UTC, Irgendwer01 commented
@pablocnvs Why did you created a new PR?

2022-08-18 22:23 UTC, pablocnvs commented
Because apparently i didn't update the repo in my laptop, so when i got to making the pr i saw there were merge conflicts. i hadn't used github for a while and i was a bit rusty, so i went for the rather lengthy process of redoing the pr.

2022-08-20 16:59 UTC, TechLord22 requested changes

2022-08-20 16:59 UTC, TechLord22 commented on src/main/java/gregicality/science/api/unification/materials/GCYSFirstDegreeMaterials.java
> +                .color(LithiumHydride.getMaterialRGB())
It'd be better to give this its own unique color.

2022-08-24 20:33 UTC, TechLord22 approved these changes

2022-08-24 20:33 UTC, merged